"""Frozen CRUD signatures (spec §4.7). Agent B implements the bodies.

Agents C and D code AGAINST these signatures and must not change them.

Two orchestrator-level notes (§0 rule 2 permits ADDING at this level, never
renaming):

1. ``generate_patient_code`` is implemented here rather than left to Agent B.
   Its body *is* the C2 contract (``^P-[0-9A-F]{6}$``, asserted by
   ``test_patient_autogen.py`` and by ``smoke_test.sh`` step 4), it touches no
   database, and a divergent implementation would break the wire contract.

2. ``find_by_idempotency_key`` is ADDED. §4.7 only lets callers look up by
   content fingerprint, but §5-C's ``test_duplicate_retry.py`` also requires
   "same ``Idempotency-Key`` + different bytes -> 409 ``idempotency_conflict``",
   which is undetectable unless the stored content hash for that key can be
   read back. Returning ``(response, content_sha256)`` keeps the predict-shaped
   dict clean instead of smuggling private keys into it.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - typing only
    from app.db.models import Patient
    from app.inference.decision import DecisionResult


def generate_patient_code() -> str:
    """'P-' + uuid4().hex[:6].upper()  (C2). FROZEN BODY — do not modify."""
    return "P-" + uuid.uuid4().hex[:6].upper()


def get_or_create_patient(session: Any, patient_code: str) -> "Patient":
    raise NotImplementedError("Agent B (§5-B B3)")


def create_exam_with_result(
    session: Any,
    *,
    exam_id: str,
    patient_code: str | None,
    eye: str | None,
    image_path: str,
    content_sha256: str,
    quality: str,
    blur_var: float | None,
    mean_gray: float | None,
    result: "DecisionResult",
    model_version: str,
    heatmap_path: str | None,
    processed_at: datetime,
    idempotency_key: str | None = None,
) -> None:
    """One transaction. patient_code may already be server-generated by caller.

    Writes ``result.db_probability`` / ``result.db_icdr_grade`` (NULL for
    UNGRADABLE, C3) while ``referable``/``decision`` are always stored, and
    appends one ``audit_log`` row (``action='predict'``) in the same
    transaction.
    """
    raise NotImplementedError("Agent B (§5-B B3)")


def find_recent_duplicate(
    session: Any,
    *,
    content_sha256: str,
    patient_code: str | None,
    eye: str | None,
    window_min: int,
) -> dict | None:
    """C14: predict-shaped dict of the newest matching exam inside the window, else None."""
    raise NotImplementedError("Agent B (§5-B B3)")


def find_by_idempotency_key(
    session: Any,
    *,
    idempotency_key: str,
    window_min: int,
) -> tuple[dict, str] | None:
    """ADDED (see module docstring). Newest exam stored under this key inside
    the window, as ``(predict_shaped_dict, content_sha256)``; ``None`` if absent.
    """
    raise NotImplementedError("Agent B (§5-B B3)")


def list_exams(
    session: Any,
    limit: int = 50,
    offset: int = 0,
    patient_code: str | None = None,
) -> list[dict]:
    raise NotImplementedError("Agent B (§5-B B3)")


def get_exam(session: Any, exam_id: str) -> dict | None:
    """Returns predict-shaped dict (§4.3 keys) or None."""
    raise NotImplementedError("Agent B (§5-B B3)")
